# Generated by Django 5.0.1 on 2024-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthInfo',
            fields=[
                ('shop_name', models.TextField(primary_key=True, serialize=False)),
                ('token', models.TextField(null=True)),
                ('token_expiry', models.DateTimeField(null=True)),
                ('mint_url', models.URLField(null=True)),
                ('request_headers', models.JSONField(null=True)),
                ('request_body', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchInfo',
            fields=[
                ('shop_name', models.TextField(primary_key=True, serialize=False)),
                ('base_url', models.URLField()),
                ('request_headers', models.JSONField(null=True)),
            ],
        ),
    ]
