# Generated by Django 5.0.1 on 2024-03-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authinfo',
            name='token',
        ),
    ]
