# Generated by Django 5.0.1 on 2024-03-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_search', '0002_remove_authinfo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfo',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
