# Generated by Django 5.0.1 on 2024-02-22 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("shopping_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglistitem",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
