version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=project_db
      - POSTGRES_USER=decdophobia-admin
      - POSTGRES_PASSWORD=password1
    ports:
      - 5432:5432

volumes:
  postgres_data: