# Generated by Django 5.0.1 on 2024-02-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview_pictue",
            field=models.ImageField(
                blank=True, null=True, upload_to="./product_photos"
            ),
        ),
    ]
