# Generated by Django 5.0.1 on 2024-02-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_preview_pictue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="preview_pictue",
            new_name="preview_picture",
        ),
    ]
