# Generated by Django 5.0.1 on 2024-02-04 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('customerReview', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('shippingTime', models.CharField(choices=[("Doesn't matter", "Doesn't matter"), ('A couple weeks', 'A couple weeks'), ('A week or so', 'A week or so'), ('Amazon speed', 'Amazon speed'), ('Right now', 'Right now')], max_length=50)),
                ('returnPolicy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('brandReputation', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Ok', 'Ok')], max_length=10)),
            ],
        ),
    ]
